apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rds-external-secrets.yaml
  - deployment-api.yaml
  - service-api.yaml
  - route-api.yaml
  - deployment-ui.yaml
  - service-ui.yaml
  - route-ui.yaml
  - psql-client.yaml
  - probe-application/probe-application-deployment.yaml
  - probe-application/probe-application-external-secrets.yaml
  - client-application/cdc/kafka/strimzi.yaml
  - client-application/cdc/kafka/kafka-cluster.yaml
  - client-application/cdc/kafka/kafka-ui.yaml
  - client-application/cdc/kafka/connect-cluster.yaml
  - client-application/cdc/databases/postgres.yaml